// POST /api/team/invite
// Creates a pending invitation for the caller's active org.
// Body: { email: string, role: 'admin'|'operator'|'viewer' }
// Returns: { inviteUrl, invitation }
// Requires: owner | admin membership.
import { requireOrgMember, isAdmin } from '../_lib/teamAuth.js';
import { sendInviteEmail } from '../_lib/sendInviteEmail.js';

export default async function handler(req, res) {
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' });

  const auth = await requireOrgMember(req, res);
  if (!auth) return;

  const { adminClient, userId, orgId, orgRole } = auth;

  if (!isAdmin(orgRole)) {
    return res.status(403).json({ error: 'Only owners and admins can invite team members.' });
  }

  const { email, role } = req.body || {};
  if (!email || !role) return res.status(400).json({ error: 'email and role are required' });
  if (!['admin', 'operator', 'viewer'].includes(role)) {
    return res.status(400).json({ error: 'role must be admin, operator, or viewer' });
  }

  // Check seat limit
  const { data: org } = await adminClient
    .from('organizations')
    .select('plan, seat_limit')
    .eq('id', orgId)
    .single();

  if (org) {
    // Count active members + pending invites
    const { count: memberCount } = await adminClient
      .from('memberships')
      .select('id', { count: 'exact', head: true })
      .eq('organization_id', orgId)
      .eq('status', 'active');

    const { count: pendingCount } = await adminClient
      .from('organization_invitations')
      .select('id', { count: 'exact', head: true })
      .eq('organization_id', orgId)
      .eq('status', 'pending')
      .gt('expires_at', new Date().toISOString());

    const totalSeats = (memberCount || 0) + (pendingCount || 0);
    if (org.plan === 'starter') {
      return res.status(403).json({
        error: 'seat_limit_exceeded',
        message: 'Upgrade to Pro to invite teammates. Starter plans include 1 seat (Owner only).',
      });
    }
    if (org.plan !== 'scale' && totalSeats >= org.seat_limit) {
      return res.status(403).json({
        error: 'seat_limit_exceeded',
        message: `Your ${org.plan} plan has reached its seat limit of ${org.seat_limit}.`,
      });
    }
  }

  // Cancel any existing pending invitation for this email in this org
  await adminClient
    .from('organization_invitations')
    .update({ status: 'canceled' })
    .eq('organization_id', orgId)
    .eq('email', email.toLowerCase().trim())
    .eq('status', 'pending');

  // Create the new invitation (token generated by DB default)
  const { data: invitation, error: invErr } = await adminClient
    .from('organization_invitations')
    .insert({
      organization_id: orgId,
      email:           email.toLowerCase().trim(),
      role,
      invited_by:      userId,
      status:          'pending',
      expires_at:      new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    })
    .select()
    .single();

  if (invErr) return res.status(500).json({ error: invErr.message });

  const origin = req.headers.origin ||
    (process.env.VERCEL_URL ? `https://${process.env.VERCEL_URL}` : 'https://lotline-crm.vercel.app');

  const inviteUrl = `${origin}/invite/${invitation.token}`;

  // Fetch org name + inviter name for the email
  const [{ data: orgData }, { data: inviterProfile }] = await Promise.all([
    adminClient.from('organizations').select('name').eq('id', orgId).single(),
    adminClient.from('profiles').select('name').eq('id', userId).single(),
  ]);

  await sendInviteEmail({
    to:          invitation.email,
    inviteUrl,
    orgName:     orgData?.name || 'your team',
    role,
    inviterName: inviterProfile?.name,
  });

  return res.status(200).json({ inviteUrl, invitation });
}
